### ISSUE TITLE
Check failed: Cr::Utility::Directory::exists(physicsFilename) 

### ISSUE THREAD

**Issue by ZhuFengdaaa** [saimwani/multiON#1]
```
<print configs>
2020-12-16 20:38:56,165 Initializing dataset MultiNav-v1
2020-12-16 20:38:57,335 Initializing dataset MultiNav-v1
2020-12-16 20:38:57,355 initializing sim Sim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1216 20:38:57.356987 16952 Simulator.cpp:64] Loading navmesh from data/scene_datasets/mp3d/2t7WUuJeko7/2t7WUuJeko7.navmesh
I1216 20:38:57.357069 16952 Simulator.cpp:66] Loaded.
I1216 20:38:57.357087 16952 SceneGraph.h:92] Created DrawableGroup: 
Renderer: GeForce RTX 2070/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 418.56
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
F1216 20:38:57.398231 16952 ResourceManager.cpp:340] Check failed: Cr::Utility::Directory::exists(physicsFilename) 
*** Check failure stack trace: ***
Traceback (most recent call last):
  File "habitat_baselines/run.py", line 91, in <module>
    main()
  File "habitat_baselines/run.py", line 43, in main
    run_exp(**vars(args))
  File "habitat_baselines/run.py", line 88, in run_exp
    trainer.eval()
  File "/home/dm/multiON/habitat_baselines/common/base_trainer.py", line 289, in eval
    checkpoint_index=prev_ckpt_ind,
  File "/home/dm/multiON/habitat_baselines/rl/ppo/ppo_trainer.py", line 1376, in _eval_checkpoint
    self.envs = construct_envs(config, get_env_class(config.ENV_NAME))
  File "/home/dm/multiON/habitat_baselines/common/env_utils.py", line 111, in construct_envs
    env_fn_args=tuple(tuple(zip(configs, env_classes))),
  File "/home/dm/multiON/habitat/core/vector_env.py", line 136, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/home/dm/multiON/habitat/core/vector_env.py", line 136, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7f9a64bad050>
Traceback (most recent call last):
  File "/home/dm/multiON/habitat/core/vector_env.py", line 469, in __del__
    self.close()
  File "/home/dm/multiON/habitat/core/vector_env.py", line 351, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/dm/anaconda3/envs/habitat2/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

```
my Nvidia and CUDA configuration: 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   49C    P8     6W / 175W |    366MiB /  7949MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by saimwani** [comment]
It seems like object insertion in Habitat Sim is not working. Was Habitat Sim installed without errors? You can follow [this tutorial](https://github.com/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/rigid_object_tutorial.ipynb) for object insertion in Habitat Sim to verify if you are able to insert rigid objects.

**Comment by ZhuFengdaaa** [comment]
Yes, I rebuild the habitat-sim and now it works. Thanks.
