### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by kyhfirefly** [saimwani/multiON#13]
I run the evaluation code on python 3.8.20, pytorch v1.8.0, and CUDA V11.1.74. My problem is exactly the same as the [issue](https://github.com/saimwani/multiON/issues/1), the error message is as follows.

> Traceback (most recent call last):
  File "habitat_baselines/run.py", line 94, in <module>
    main()
  File "habitat_baselines/run.py", line 46, in main
    run_exp(**vars(args))
  File "habitat_baselines/run.py", line 91, in run_exp
    trainer.eval()
  File "/home/kyh/multion/multiON/habitat_baselines/common/base_trainer.py", line 286, in eval
    self._eval_checkpoint(
  File "/home/kyh/multion/multiON/habitat_baselines/rl/ppo/ppo_trainer.py", line 1376, in _eval_checkpoint
    self.envs = construct_envs(config, get_env_class(config.ENV_NAME))
  File "/home/kyh/multion/multiON/habitat_baselines/common/env_utils.py", line 108, in construct_envs
    envs = habitat.VectorEnv(
  File "/home/kyh/multion/multiON/habitat/core/vector_env.py", line 135, in __init__
    self.observation_spaces = [
  File "/home/kyh/multion/multiON/habitat/core/vector_env.py", line 136, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7fd8ce1e28b0>
Traceback (most recent call last):
  File "/home/kyh/multion/multiON/habitat/core/vector_env.py", line 469, in __del__
    self.close()
  File "/home/kyh/multion/multiON/habitat/core/vector_env.py", line 351, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/kyh/anaconda3/envs/multion/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

However, due to the update of habitat documentation and API, I was unable to check whether the environment can insert objects according to the solution given in [issue](https://github.com/saimwani/multiON/issues/1), and after successfully rebuilding the virtual environment, the above error was still output.

**Comment by saimwani** [comment]
I believe the object insertion tutorial has moved to [this notebook](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/notebooks/managed_rigid_object_tutorial.ipynb). For the older setup that this codebase follows, you can find the relevant tutorial by checking out an older commit (`5a889591e73ca1889eb84e7e7548684b516d52e6`) and following the tutorial under `habitat-sim/examples/tutorials/colabs/rigid_object_tutorial.ipynb`.

**Comment by kyhfirefly** [comment]
Thanks for your reply. Checking out an older commit (5a889591e73ca1889eb84e7e7548684b516d52e6) , I did not find the tutorial under `habitat-sim/examples/tutorials/colabs/rigid_object_tutorial.ipynb`.
![d28a5631-174f-43f3-a070-3232fb2dd940](https://github.com/user-attachments/assets/41330bc3-0e95-416c-9e7b-2811b25bef29)
When checking whether the environment can insert objects, an error occurs when creating a simulator.

> AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'scene_id'

Looking forward to your patient answer.

**Comment by saimwani** [comment]
The path was not relative, please check `examples/tutorials/colabs/rigid_object_tutorial.ipynb`. Sorry for the confusion.

**Comment by kyhfirefly** [comment]
I think the object insertion tutorials are similar regardless of which commit they are based on. Therefore, I always get the same error when I run to `cfg = make_configuration()`.
> AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'scene_id'

The explanations related to this error in habitat issues are all related to the version. Do I need to rebuild habitat-sim after checking out an older commit 5a889591e73ca1889eb84e7e7548684b516d52e6? If not, how can I solve the above error?
I also tested the results of rebuilding the environment after checking out, and found that running `import habitat_sim` would result in an error.
> ImportError: generic_type: type "SceneNode" referenced unknown base type "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicTranslationRotationScalingTransformation3D<float> >"

**Comment by kyhfirefly** [comment]
I solved the above problem. It was not an environment dependency issue, but I did not download default.phys_scene_config.json when I manually downloaded the dataset.
